### PR TITLE
Add a Jamf Pro Custom Schema for super

### PR DESCRIPTION
**Pull request by wakco**
Add a custom schema for Jamf Pro, to enable managing super without having to deal with the raw plist content for settings.

This intentionally does not include the free space or battery settings as they are designed for testing purposes only, but does include every other setting according to the super scripts help command. They can be added with the Custom Property option when adding/removing properties.

### CODE REVIEW

**Comment by wakco** [comment]
I started with the other guys version for super v2, removed all the Configured/Not Configured stuff, and otherwise cleaned it up as best I could before updating it for v3.

**Comment by wakco** [comment]
missed ErrorDefer, working on adding it now

**Comment by wakco** [comment]
When I had started this, I had forgotten to the help in the script also shows the setting type, so I had errantly set some to integer, this is now fixed.

**Comment by wakco** [comment]
One last thing, TestMode defaults to true, to make sure people are seeing the settings they need and to make sure they turn it off (or remove the property) before deployment.

**Review by Macjutsu — APPROVED** [review]
I uploaded... looks good... thanks!

**Comment by dmote75** [comment]
@wakco Hi Richard, this is really cool. I added this to JAMF and looks nice. Have t had a chance to really get into it, but will later. Saw you just had an update so will get it updated. 
One question: I saw in the JSON it mentioned the different Defer options (Soft, Hard, Focus; Count, Days, Date) but I don't see that as options setting up the Config Profile (I think a few other things but can't remember them right now). Am I missing something? Very well could have done something wrong.

**Comment by wakco** [comment]
Check add/remove properties, it's configured to clear empty properties, so if you save before setting anything, a lot of them will appear to disappear, just re-add them.

**Comment by swissarmygeek** [comment]
Hello, I have updated the Jamf Pro Custom Schema for SUPER, for v4.0.3, if you would like to add it.  I started with the existing 'v4.0.0-beta2' but then revised the text for most options (copying text from the wiki) and added all of the missing Config Profile items (I even extracted key names from super itself to make sure I hadn't missed any)

[Jamf-Pro-External-Application-Custom-Schema-com.macjutsu.super-v4.0.3.json](https://github.com/Macjutsu/super/files/14398059/Jamf-Pro-External-Application-Custom-Schema-com.macjutsu.super-v4.0.3.json)

**Pull request merged**
