### PR TITLE
language selection and german translation added

### PR DESCRIPTION
**Pull request by SteveKueng**
I have added a simple speech recognition function and translated super into German.
It is easy to add more languages. Only a new function with the translation has to be added and the switch case has to be extended.

### CODE REVIEW

**Comment by nonos456** [comment]
Hi, I am very interested in implementing language choice. But can you explain to me how I should do it?

**Comment by nonos456** [comment]
Hi,

I see that you have not translated the messages from line 7400 to line 7412 of your script modification. is there a reason or is this an oversight?

**Comment by SteveKueng** [comment]
sorry didn't see the comment.
yes, I overlooked it. I'll update it right away

**Comment by Macjutsu** [comment]
First, thank you for taking the time to add localization.

However, I've already moved on to v4.1 betas, and while I do have plans to support localization in the future, I don't want it directly in the script. My plans are to allow for external localization configuration files.

**Comment by nonos456** [comment]
Hi,

I'm trying to do the German translation for the super 5 version. I'm OK with the text. However, I don't understand why you deleted ${display_string_deferral_button} on lines 7927, 7929, 7931, 7933, 7935, 7937 and 7939 of the version 4.0.3 script?

**Pull request closed without merging**
